GET http://localhost:3000/api/reportes


###Insertar datos
POST http://localhost:3000/api/reportes
Content-Type: application/json

{
  "id_usuario": 1,
  "Id_ubicacion": 1,
  "id_crimen": 1,
  "descripcion": "Robo de bicicleta en el parque",
  "ubi_lat": 6.25184,
  "ubi_lng": -75.56359,
  "Id_estado": 1
}

###

GET http://localhost:3000/api/usuarios
###
POST http://localhost:3000/api/usuarios
Content-Type: application/json

{
  "nombre": "Camilo pablo",
  "apellido": "Perez Pereira",
  "email": "PerezPerreira@gmail.com",
  "contrasenia": "5489635asdaw",
  "rol": 1,
  "fechaRegistro": "2025-04-15 15:00:00",
  "fechaNacimiento": "2002-04-12"
}

###Eliminar usuario
DELETE http://localhost:3000/api/usuarios/9

