GET http://localhost:3000/api/reportes


###Insertar datos
POST http://localhost:3000/api/reportes
Content-Type: application/json

{
  "id_usuario": 1,
  "Id_ubicacion": 1,
  "id_crimen": 1,
  "descripcion": "Robo de bicicleta en el parque",
  "ubi_lat": 6.25184,
  "ubi_lng": -75.56359,
  "Id_estado": 1
}


###

